def write_correct_rules(f):
    """Write the correct Prolog rules to the file."""
    # First, write the discontiguous declarations
    f.write("% Discontiguous declarations to suppress warnings\n")
    f.write(":- discontiguous parent_of/2.\n")
    f.write(":- discontiguous male/1.\n")
    f.write(":- discontiguous female/1.\n")
    f.write(":- discontiguous sibling_of/2.\n")
    f.write(":- discontiguous half_sibling_of/2.\n")
    f.write(":- discontiguous brother_of/2.\n")
    f.write(":- discontiguous sister_of/2.\n")
    f.write(":- discontiguous uncle_of/2.\n")
    f.write(":- discontiguous aunt_of/2.\n")
    f.write(":- discontiguous niece_of/2.\n")
    f.write(":- discontiguous nephew_of/2.\n")
    f.write(":- discontiguous cousin_of/2.\n")
    f.write(":- discontiguous relative/2.\n")
    f.write(":- discontiguous ancestor_of/2.\n")
    f.write(":- discontiguous grandparent_of/2.\n")
    f.write(":- discontiguous grandchild_of/2.\n")
    f.write(":- discontiguous grandmother_of/2.\n")
    f.write(":- discontiguous grandfather_of/2.\n")
    f.write(":- discontiguous granddaughter_of/2.\n")
    f.write(":- discontiguous grandson_of/2.\n")
    f.write(":- discontiguous father_of/2.\n")
    f.write(":- discontiguous mother_of/2.\n")
    f.write(":- discontiguous child_of/2.\n")
    f.write(":- discontiguous son_of/2.\n")
    f.write(":- discontiguous daughter_of/2.\n")
    f.write(":- discontiguous half_brother_of/2.\n")
    f.write(":- discontiguous half_sister_of/2.\n")
    f.write(":- discontiguous impossible_circular/2.\n")
    f.write(":- discontiguous incestual_sibling_parent/2.\n\n")
    
    f.write("% ========================================\n")
    f.write("% Basic Parent-Child Relationships\n")
    f.write("% ========================================\n")
    f.write("father_of(X, Y) :- parent_of(X, Y), male(X), X \\= Y.\n")
    f.write("mother_of(X, Y) :- parent_of(X, Y), female(X), X \\= Y.\n")
    f.write("child_of(Y, X) :- parent_of(X, Y), X \\= Y.\n")
    f.write("son_of(Y, X) :- child_of(Y, X), male(Y).\n")
    f.write("daughter_of(Y, X) :- child_of(Y, X), female(Y).\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Sibling Relationships\n")
    f.write("% ========================================\n")
    f.write("sibling_of(X, Y) :- parent_of(Z, X), parent_of(Z, Y), X \\= Y, Z \\= X, Z \\= Y.\n")
    f.write("brother_of(X, Y) :- sibling_of(X, Y), male(X).\n")
    f.write("sister_of(X, Y) :- sibling_of(X, Y), female(X).\n")
    f.write("\n")
    f.write("% Half-sibling relationships\n")
    f.write("half_sibling_of(X, Y) :- parent_of(Z, X), parent_of(Z, Y), X \\= Y, parent_of(W1, X), parent_of(W2, Y), W1 \\= W2, W1 \\= Z, W2 \\= Z.\n")
    f.write("half_brother_of(X, Y) :- half_sibling_of(X, Y), male(X).\n")
    f.write("half_sister_of(X, Y) :- half_sibling_of(X, Y), female(X).\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Grandparent-Grandchild Relationships\n")
    f.write("% ========================================\n")
    f.write("grandparent_of(X, Y) :- parent_of(X, Z), parent_of(Z, Y), X \\= Y.\n")
    f.write("grandmother_of(X, Y) :- grandparent_of(X, Y), female(X).\n")
    f.write("grandfather_of(X, Y) :- grandparent_of(X, Y), male(X).\n")
    f.write("grandchild_of(Y, X) :- grandparent_of(X, Y), X \\= Y.\n")
    f.write("granddaughter_of(Y, X) :- grandchild_of(Y, X), female(Y).\n")
    f.write("grandson_of(Y, X) :- grandchild_of(Y, X), male(Y).\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Uncle/Aunt - Niece/Nephew Relationships\n")
    f.write("% ========================================\n")
    f.write("uncle_of(X, Y) :- brother_of(X, Z), parent_of(Z, Y), X \\= Y.\n")
    f.write("aunt_of(X, Y) :- sister_of(X, Z), parent_of(Z, Y), X \\= Y.\n")
    f.write("niece_of(Y, X) :- female(Y), uncle_of(X, Y), X \\= Y.\n")
    f.write("niece_of(Y, X) :- female(Y), aunt_of(X, Y), X \\= Y.\n")
    f.write("nephew_of(Y, X) :- male(Y), uncle_of(X, Y), X \\= Y.\n")
    f.write("nephew_of(Y, X) :- male(Y), aunt_of(X, Y), X \\= Y.\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Half-Sibling Uncle/Aunt Relationships\n")
    f.write("% ========================================\n")
    f.write("uncle_of(X, Y) :- half_brother_of(X, Z), parent_of(Z, Y), X \\= Y.\n")
    f.write("aunt_of(X, Y) :- half_sister_of(X, Z), parent_of(Z, Y), X \\= Y.\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Grandparent Inference from Uncle/Aunt\n")
    f.write("% ========================================\n")
    f.write("grandfather_of(X, Y) :- uncle_of(X, Z), parent_of(Z, Y), male(X), X \\= Y.\n")
    f.write("grandmother_of(X, Y) :- aunt_of(X, Z), parent_of(Z, Y), female(X), X \\= Y.\n")
    f.write("\n")
    


    
    f.write("% ========================================\n")
    f.write("% Cousin Relationships\n")
    f.write("% ========================================\n")
    f.write("cousin_of(X, Y) :- parent_of(Z1, X), parent_of(Z2, Y), sibling_of(Z1, Z2), X \\= Y.\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% General Relative Relationships\n")
    f.write("% ========================================\n")
    f.write("relative(X, Y) :- parent_of(X, Y).\n")
    f.write("relative(X, Y) :- parent_of(Y, X).\n")
    f.write("relative(X, Y) :- child_of(X, Y).\n")
    f.write("relative(X, Y) :- child_of(Y, X).\n")
    f.write("relative(X, Y) :- sibling_of(X, Y).\n")
    f.write("relative(X, Y) :- sibling_of(Y, X).\n")
    f.write("relative(X, Y) :- grandparent_of(X, Y).\n")
    f.write("relative(X, Y) :- grandparent_of(Y, X).\n")
    f.write("relative(X, Y) :- uncle_of(X, Y).\n")
    f.write("relative(X, Y) :- uncle_of(Y, X).\n")
    f.write("relative(X, Y) :- aunt_of(X, Y).\n")
    f.write("relative(X, Y) :- aunt_of(Y, X).\n")
    f.write("relative(X, Y) :- cousin_of(X, Y).\n")
    f.write("relative(X, Y) :- cousin_of(Y, X).\n")
    f.write("relative(X, Y) :- half_sibling_of(X, Y).\n")
    f.write("relative(X, Y) :- half_sibling_of(Y, X).\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Ancestor-Descendant Relationships\n")
    f.write("% ========================================\n")
    f.write("ancestor_of(X, Y) :- parent_of(X, Y).\n")
    f.write("ancestor_of(X, Y) :- parent_of(X, Z), parent_of(Z, Y), X \\= Y.\n")
    f.write("ancestor_of(X, Y) :- parent_of(X, Z1), parent_of(Z1, Z2), parent_of(Z2, Y), X \\= Y, Z1 \\= Y.\n")
    f.write("\n")
    
    f.write("% ========================================\n")
    f.write("% Validation Rules (for detecting invalid relationships)\n")
    f.write("% ========================================\n")
    f.write("impossible_circular(X, Y) :- parent_of(X, Y), parent_of(Y, X).\n")
    f.write("incestual_sibling_parent(X, Y) :- sibling_of(X, Y), parent_of(X, Y).\n")
    f.write("incestual_sibling_parent(X, Y) :- sibling_of(X, Y), parent_of(Y, X).\n") 